googlegenomics/readthedocs

api-client-python/url-format.rst

Adding the right link to SNPedia

---

docs/source/_static/custom.js
docs/source/_templates/page.html
docs/source/conf.py

in a file that we do not control by moving our javascript up higher.

Work around javascript bug

---

README.md
docs/source/_static/custom.css

Per https://github.com/googlegenomics/getting-started-with-the-api/issues/5

Rename getting-started repository.

---

docs/README.md
docs/source/conf.py
docs/source/includes/dataflow_on_gce_setup.rst
docs/source/includes/dataflow_setup.rst
docs/source/pgp-data.rst
docs/source/use_cases/analyze_reads/count_reads.rst
docs/source/use_cases/analyze_reads/index.rst
docs/source/use_cases/annotate_variants/bioconductor_annotation.rst
docs/source/use_cases/annotate_variants/google_genomics_annotation.rst
docs/source/use_cases/browse_genomic_data/gabrowse.rst
docs/source/use_cases/browse_genomic_data/igv.rst
docs/source/use_cases/browse_genomic_data/index.rst
docs/source/use_cases/compute_identity_by_state/index.rst
docs/source/use_cases/compute_principal_coordinate_analysis/index.rst
docs/source/use_cases/discover_public_data/clinvar_annotations.rst
docs/source/use_cases/discover_public_data/google_genomics_public_data.rst
docs/source/use_cases/discover_public_data/index.rst
docs/source/use_cases/discover_public_data/pgp_public_data.rst
docs/source/use_cases/discover_public_data/ucsc_annotations.rst
docs/source/use_cases/load_data/load_variants.rst

Also:
* added skeleton content for CountReads Dataflow.  We'll leave it unlinked from the TOC until @iliat has a chance to fill in.
* added some guidance about run times for dataflow and spark jobs.
@mbookman please take a look http://googlegenomics.readthedocs.org/en/staging/  thanks!

Add more details to annotation pipeline sample and browsing genomic data.

---

docs/source/use_cases/analyze_reads/count_reads.rst

and add `--shardBAMReading` parameter.
@iliat Please take a look.

Remove --dataset parameter

---

docs/source/use_cases/analyze_reads/calculate_coverage.rst
docs/source/use_cases/analyze_reads/index.rst

As per @deflaux 's request, here is a simple tutorial on what the CalculateCoverage pipeline does, and how to go about running it locally on the command line.

Adding documentation for the CalculateCoverage dataflow pipeline.

---

docs/source/use_cases/browse_genomic_data/igv.rst
docs/source/use_cases/discover_public_data/pgp_public_data.rst
docs/source/use_cases/discover_public_data/supercentenarians.rst

Also a type fix and add the PGP dataset which has reads.

Update IGV link.

---

docs/source/use_cases/analyze_reads/index.rst
docs/source/use_cases/analyze_variants/index.rst
docs/source/use_cases/annotate_variants/bioconductor_annotation.rst
docs/source/use_cases/annotate_variants/index.rst
docs/source/use_cases/browse_genomic_data/bioconductor.rst
docs/source/use_cases/browse_genomic_data/gabrowse.rst
docs/source/use_cases/browse_genomic_data/index.rst
docs/source/use_cases/load_data/index.rst

Also added more detail regarding browsing genomic data.

Add a tiny blurb to all task group pages.

---

docs/source/conf.py
docs/source/includes/collapsible_dataflow_setup_instructions.rst
docs/source/includes/collapsible_spark_setup_instructions.rst
docs/source/includes/dataflow_on_gce_setup.rst
docs/source/includes/dataflow_setup.rst
docs/source/includes/get_client_secrets.rst
docs/source/includes/r_workbench_details.rst
docs/source/includes/r_workbench_setup.rst
docs/source/includes/spark_setup.rst
docs/source/use_cases/analyze_reads/calculate_coverage.rst
docs/source/use_cases/analyze_reads/count_reads.rst
docs/source/use_cases/annotate_variants/google_genomics_annotation.rst
docs/source/use_cases/annotate_variants/tute_annotation.rst
docs/source/use_cases/compute_identity_by_state/index.rst
docs/source/use_cases/compute_principal_coordinate_analysis/1-way-pca.rst
docs/source/use_cases/compute_principal_coordinate_analysis/2-way-pca.rst
docs/source/use_cases/discover_public_data/pgp_public_data.rst
docs/source/use_cases/discover_public_data/tute_genomics_public_data.rst
docs/source/use_cases/load_data/load_variants.rst
docs/source/workshops/bioc-2015.rst

Also factored out collapsible widgets from include content.

Switch all includes to absolute paths.

---

docs/source/api-client-python/getting-started-windows.rst
docs/source/conf.py
docs/source/includes/gcloud_setup.rst
docs/source/includes/gcp_signup.rst
docs/source/includes/genomics_tools_setup.rst
docs/source/includes/r_workbench_details.rst
docs/source/includes/r_workbench_setup.rst
docs/source/use_cases/analyze_reads/calculate_coverage.rst
docs/source/use_cases/analyze_reads/count_reads.rst
docs/source/use_cases/annotate_variants/bioconductor_annotation.rst
docs/source/use_cases/annotate_variants/google_genomics_annotation.rst
docs/source/use_cases/browse_genomic_data/bioconductor.rst
docs/source/use_cases/browse_genomic_data/gabrowse.rst
docs/source/use_cases/build_your_own_api_client/index.rst
docs/source/use_cases/compute_identity_by_state/index.rst
docs/source/use_cases/compute_principal_coordinate_analysis/1-way-pca.rst
docs/source/use_cases/compute_principal_coordinate_analysis/2-way-pca.rst
docs/source/use_cases/load_data/load_variants.rst
docs/source/use_cases/run_picard_and_gatk/index.rst
docs/source/workshops/bioc-2015.rst

* Pulled more setup instructions into include files.
* Also centralized more external links.
* Changed dataset links to point to RTD.

More refactoring for reuse.

---

README.md
docs/README.md
docs/source/conf.py
docs/source/github_index.rst
docs/source/index.rst
docs/source/use_cases/analyze_variants/data_analysis_codelab.rst
docs/source/use_cases/discover_public_data/genomic_data_toc.rst

@jasontiller3 I reorganized this content per your feedback.
Please take a look at and let me know if you have further suggestions, thanks!
* https://github.com/googlegenomics/start-here/tree/staging
* http://googlegenomics.readthedocs.org/en/staging/index.html
* http://googlegenomics.readthedocs.org/en/staging/github_index.html

Move repository list into RTD.

---

docs/source/includes/gcloud_compute_configure.rst
docs/source/includes/gcp_signup.rst
docs/source/includes/get_client_secrets.rst
docs/source/includes/r_workbench_setup.rst
docs/source/use_cases/discover_public_data/genomic_data_toc.rst
docs/source/workshops/bioc-2015.rst

. . . in preparation for the next round of updates.

Merge latest Bioc workshop updates

---

docs/source/github_index.rst
docs/source/index.rst
docs/source/workshops/index.rst

This will be changed again when we restructure the whole toctree but I wanted to get the workshop in there somewhere for Tuesday.
Please update this PR directly or make a new one if the toctree structure could be more clear - thanks!

Get workshop into toctree.

---

docs/source/use_cases/perform_quality_control_checks/index.rst
docs/source/use_cases/perform_quality_control_checks/verify_bam_id.rst

To be merged into master at the same time as the verifyBamId branch in dataflow-java
https://github.com/googlegenomics/dataflow-java/tree/verifyBamId

Adding instructions for VerifyBamId

---

docs/source/conf.py
docs/source/index.rst
docs/source/use_cases/perform_quality_control_checks/verify_bam_id.rst
docs/source/use_cases/run_familiar_tools/index.rst
docs/source/use_cases/run_familiar_tools/ncbiblast.rst

Also rearranged TOC a bit http://googlegenomics.readthedocs.org/en/staging/
The TOC still feels a bit off since most topics on [Run Familiar Tools](http://googlegenomics.readthedocs.org/en/staging/use_cases/run_familiar_tools/index.html) start with a verb but not all.

Add NCBI Blast.

---

docs/source/includes/bioconductor_docker_details.rst
docs/source/sections/process_data.rst
docs/source/use_cases/analyze_reads/calculate_coverage.rst
docs/source/use_cases/analyze_variants/analyze_variants_with_bigquery.rst
docs/source/use_cases/analyze_variants/transition_transversion.rst
docs/source/use_cases/annotate_variants/bioconductor_annotation.rst
docs/source/use_cases/browse_genomic_data/bioconductor.rst
docs/source/use_cases/discover_public_data/1000_genomes.rst
docs/source/use_cases/discover_public_data/clinvar_annotations.rst
docs/source/use_cases/discover_public_data/reference_genomes.rst
docs/source/use_cases/discover_public_data/ucsc_annotations.rst
docs/source/use_cases/perform_quality_control_checks/verify_bam_id.rst
docs/source/use_cases/run_familiar_tools/bioconductor.rst
docs/source/use_cases/run_familiar_tools/ncbiblast.rst
docs/source/workshops/bioc-2015.rst

See updated TOC on http://googlegenomics.readthedocs.org/en/staging/sections/process_data.html
Also took a big bite out of https://github.com/googlegenomics/readthedocs/issues/83

Add Bioconductor and Datalab to new TOC.

---

docs/source/use_cases/run_picard_and_gatk/index.rst

Old:
* http://googlegenomics.readthedocs.org/en/latest/index.html
* http://googlegenomics.readthedocs.org/en/latest/sections/access_data.html
New: 
* http://googlegenomics.readthedocs.org/en/staging/index.html
* http://googlegenomics.readthedocs.org/en/staging/sections/access_data.html

Fix section leveling.

---

docs/source/add_message_read_on_rtd.py
docs/source/sections/access_data.rst
docs/source/sections/analyze_data.rst
docs/source/sections/learn_more.rst
docs/source/sections/process_data.rst
docs/source/sections/select_genomic_data.rst
docs/source/use_cases/getting-started-with-the-api/go.rst
docs/source/use_cases/getting-started-with-the-api/java.rst
docs/source/use_cases/getting-started-with-the-api/python.rst
docs/source/use_cases/perform_quality_control_checks/verify_bam_id.rst
docs/source/use_cases/setup_gridengine_cluster_on_compute_engine/preemptible_vms.rst

Update add_message_read_on_rtd to handle "Go" page (only two "==" for title).
Update add_message_read_on_rtd to include processing the "sections".
Ran add_message_read_on_rtd to pick up new content.

add_message_read_on_rtd updates for new pages

---

docs/source/includes/collapsible_get_client_secrets.rst
docs/source/includes/collapsible_get_client_secrets_json.rst
docs/source/includes/genomics_tools_setup.rst
docs/source/includes/get_client_secrets.rst
docs/source/includes/get_client_secrets_json.rst
docs/source/includes/get_client_secrets_steps.rst
docs/source/use_cases/run_picard_and_gatk/index.rst
docs/source/use_cases/setup_gridengine_cluster_on_compute_engine/index.rst

Also the instructions concluded with downloading the client_secrets.json-
it should just focus on getting the client id and secret.
If we need another version that involves downloading the file, we
should create a get_client_secrets_json.rst.

Updates get_client_secrets.rst to match the latest UI.

---

docs/source/use_cases/setup_gridengine_cluster_on_compute_engine/index.rst

Add documentation about noauth_local_webserver.

---

docs/source/use_cases/analyze_reads/calculate_coverage.rst

Fixes https://github.com/googlegenomics/readthedocs/issues/96

Update sample to run on Platinum Genomes.

---

docs/source/conf.py
docs/source/includes/dataflow_details.rst
docs/source/includes/dataflow_on_gce_run.rst
docs/source/includes/dataflow_on_gce_setup.rst
docs/source/includes/dataflow_setup.rst
docs/source/includes/spark_details.rst
docs/source/includes/spark_setup.rst
docs/source/use_cases/analyze_reads/calculate_coverage.rst
docs/source/use_cases/analyze_reads/count_reads.rst
docs/source/use_cases/compute_identity_by_state/index.rst
docs/source/use_cases/compute_principal_coordinate_analysis/1-way-pca.rst
docs/source/use_cases/compute_principal_coordinate_analysis/2-way-pca.rst
docs/source/use_cases/perform_quality_control_checks/verify_bam_id.rst

This can be merged after a release is built from https://github.com/googlegenomics/dataflow-java/pull/160

Update pipeline instructions for ALPN and auth.

---

docs/source/includes/bioconductor_deployment_sidebar.rst
docs/source/use_cases/discover_public_data/1000_genomes.rst
docs/source/use_cases/discover_public_data/dream_smc_dna.rst
docs/source/use_cases/discover_public_data/pgp_public_data.rst
docs/source/use_cases/discover_public_data/platinum_genomes.rst
docs/source/use_cases/discover_public_data/simons_foundation.rst
docs/source/use_cases/discover_public_data/supercentenarians.rst

Also update API explorer links to V1.

Add additional information about the data disk for Bioconductor on GCE.

---

docs/source/use_cases/discover_public_data/1000_genomes.rst
docs/source/use_cases/run_familiar_tools/bioconductor.rst

Also add resize VM instructions for Bioconductor.

Add details for 1,000 Genomes phase 3 variants release 20150220.

---

docs/source/conf.py
docs/source/sections/advanced_bigquery.rst
docs/source/sections/analyze_data.rst
docs/source/use_cases/analyze_variants/gwas.rst
docs/source/use_cases/analyze_variants/index.rst
docs/source/use_cases/annotate_variants/annovar.rst
docs/source/use_cases/annotate_variants/bioconductor_annotation.rst
docs/source/use_cases/annotate_variants/interval_joins.rst
docs/source/use_cases/annotate_variants/tute_annotation.rst
docs/source/use_cases/load_data/multi_sample_variants.rst

Add more BigQuery topics.

---

docs/source/use_cases/annotate_variants/annovar.rst
docs/source/use_cases/linkage_disequilibrium/public_ld_datasets.rst

Great script from @gregmcinnes!

Add a link to VCF formatting script.

---

docs/source/migrating_v1beta2_to_v1.rst
docs/source/sections/learn_more.rst

Miscellaneous updates to the migration guide.

Add v1beta2 -> v1 migration guide to the TOC.

---

docs/source/use_cases/annotate_variants/interval_joins.rst

Preview here: http://googlegenomics.readthedocs.io/en/staging/use_cases/annotate_variants/interval_joins.html
Change-Id: I375b4dd734443c8f317e3f6d84a26f67126d7d76

Port interval JOIN to standard SQL.

---

docs/source/use_cases/discover_public_data/simons_foundation.rst

Change-Id: Ic4baa6f4f803175305de50cb391dbf9103ebc178

Add details for Simons Genome Diversity Project data.

---

docs/source/conf.py
docs/source/use_cases/discover_public_data/1000_cannabis_genomes.rst
docs/source/use_cases/discover_public_data/genomic_data_toc.rst

Also remove obsolete Sphinx warning suppression code.
Staged on http://googlegenomics.readthedocs.io/en/staging/use_cases/discover_public_data/1000_cannabis_genomes.html
Change-Id: Id1421ab549f0aa3bcbf5f618a471a041e20818f7

Add open cannabis genomes project.

---

docs/source/use_cases/discover_public_data/annotations_toc.rst
docs/source/use_cases/discover_public_data/cosmic_annotations.rst
docs/source/use_cases/discover_public_data/isb_cgc_data.rst

Also update ISB-CGC public data location.
Staged here: http://googlegenomics.readthedocs.io/en/staging/use_cases/discover_public_data/cosmic_annotations.html
Change-Id: Ibc630864cfe2c8701f21bcc2f9ae6f4ea581be33

Add COSMIC.

---

docs/source/use_cases/discover_public_data/dream_smc_dna.rst

Fixes https://github.com/googlegenomics/readthedocs/issues/151

Fix broken link
